disabled_rules:
- trailing_whitespace
- force_cast

opt_in_rules:
- attributes
- closure_end_indentation
- closure_spacing
- conditional_returns_on_newline
- empty_count
- explicit_init
- explicit_type_interface
- fatal_error_message
- first_where
- implicitly_unwrapped_optional
- missing_docs
- nimble_operator
- number_separator
- object_literal
- operator_usage_whitespace
- overridden_super_call
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- switch_case_on_newline
- valid_docs

excluded:
- Pods/
- Carthage/
- e-sleepTests/
- e-sleepUITests/
- R.generated.swift

line_length: 300

identifier_name:
  min_length: 1
